# Generated by Django 5.0 on 2024-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderly', '0002_api_keys_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='api_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
