# Generated by Django 4.2.11 on 2024-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderly', '0004_reguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.TextField()),
                ('ambulance_number', models.IntegerField()),
                ('driver_number', models.IntegerField()),
                ('Location', models.CharField(max_length=15)),
            ],
        ),
    ]
