# Generated by Django 4.2.11 on 2024-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderly', '0005_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance_book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.TextField()),
                ('ambulance_num', models.TextField()),
                ('driver_mobile', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ambulance',
        ),
    ]
